development:
  clients:
    default:
      database: example_mongo
      username: 'ks_desa'
      password: 'KSDesa1@'
      hosts:
        - 192.168.1.10:27017
      options:
        max_pool_size: 5
        min_pool_size: 1
  options:
    raise_not_found_error: false

test:
  clients:
    default:
      database: example_mongo_test
      hosts:
        - 192.168.1.10:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1